// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: post.proto

package post_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserPostList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostList []*Post `protobuf:"bytes,1,rep,name=PostList,proto3" json:"PostList,omitempty"`
}

func (x *UserPostList) Reset() {
	*x = UserPostList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPostList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostList) ProtoMessage() {}

func (x *UserPostList) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostList.ProtoReflect.Descriptor instead.
func (*UserPostList) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

func (x *UserPostList) GetPostList() []*Post {
	if x != nil {
		return x.PostList
	}
	return nil
}

type Post struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int32  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PostText string `protobuf:"bytes,2,opt,name=PostText,proto3" json:"PostText,omitempty"`
}

func (x *Post) Reset() {
	*x = Post{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *Post) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Post) GetPostText() string {
	if x != nil {
		return x.PostText
	}
	return ""
}

type PostPbStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FolloweeUserIDsList []int32 `protobuf:"varint,1,rep,packed,name=FolloweeUserIDsList,proto3" json:"FolloweeUserIDsList,omitempty"` // users whose post we want
	AddPostStatus       bool    `protobuf:"varint,2,opt,name=AddPostStatus,proto3" json:"AddPostStatus,omitempty"`
}

func (x *PostPbStruct) Reset() {
	*x = PostPbStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_post_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostPbStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPbStruct) ProtoMessage() {}

func (x *PostPbStruct) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPbStruct.ProtoReflect.Descriptor instead.
func (*PostPbStruct) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{2}
}

func (x *PostPbStruct) GetFolloweeUserIDsList() []int32 {
	if x != nil {
		return x.FolloweeUserIDsList
	}
	return nil
}

func (x *PostPbStruct) GetAddPostStatus() bool {
	if x != nil {
		return x.AddPostStatus
	}
	return false
}

var File_post_proto protoreflect.FileDescriptor

var file_post_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x6f,
	0x73, 0x74, 0x5f, 0x70, 0x62, 0x22, 0x39, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70,
	0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x3a, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x65, 0x78, 0x74, 0x22, 0x66, 0x0a, 0x0c,
	0x50, 0x6f, 0x73, 0x74, 0x50, 0x62, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x30, 0x0a, 0x13,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x13, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24,
	0x0a, 0x0d, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x32, 0xf5, 0x01, 0x0a, 0x0c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x6f, 0x73, 0x74,
	0x5f, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x62, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x1a, 0x15, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x50, 0x6f, 0x73, 0x74, 0x12, 0x0d, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x62, 0x2e, 0x50,
	0x6f, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x62, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0d,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x0d, 0x2e,
	0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70,
	0x6f, 0x73, 0x74, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x62, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50,
	0x6f, 0x73, 0x74, 0x73, 0x12, 0x0d, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x62, 0x2e, 0x50,
	0x6f, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x62, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData = file_post_proto_rawDesc
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(file_post_proto_rawDescData)
	})
	return file_post_proto_rawDescData
}

var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_post_proto_goTypes = []interface{}{
	(*UserPostList)(nil), // 0: post_pb.UserPostList
	(*Post)(nil),         // 1: post_pb.Post
	(*PostPbStruct)(nil), // 2: post_pb.PostPbStruct
}
var file_post_proto_depIdxs = []int32{
	1, // 0: post_pb.UserPostList.PostList:type_name -> post_pb.Post
	2, // 1: post_pb.PostsService.GetFolloweePosts:input_type -> post_pb.PostPbStruct
	1, // 2: post_pb.PostsService.AddPost:input_type -> post_pb.Post
	1, // 3: post_pb.PostsService.ClearAllPosts:input_type -> post_pb.Post
	1, // 4: post_pb.PostsService.GetAllPosts:input_type -> post_pb.Post
	0, // 5: post_pb.PostsService.GetFolloweePosts:output_type -> post_pb.UserPostList
	0, // 6: post_pb.PostsService.AddPost:output_type -> post_pb.UserPostList
	2, // 7: post_pb.PostsService.ClearAllPosts:output_type -> post_pb.PostPbStruct
	0, // 8: post_pb.PostsService.GetAllPosts:output_type -> post_pb.UserPostList
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_post_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPostList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Post); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_post_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostPbStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_post_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_rawDesc = nil
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PostsServiceClient is the client API for PostsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostsServiceClient interface {
	GetFolloweePosts(ctx context.Context, in *PostPbStruct, opts ...grpc.CallOption) (*UserPostList, error)
	AddPost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*UserPostList, error)
	ClearAllPosts(ctx context.Context, in *Post, opts ...grpc.CallOption) (*PostPbStruct, error)
	GetAllPosts(ctx context.Context, in *Post, opts ...grpc.CallOption) (*UserPostList, error)
}

type postsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostsServiceClient(cc grpc.ClientConnInterface) PostsServiceClient {
	return &postsServiceClient{cc}
}

func (c *postsServiceClient) GetFolloweePosts(ctx context.Context, in *PostPbStruct, opts ...grpc.CallOption) (*UserPostList, error) {
	out := new(UserPostList)
	err := c.cc.Invoke(ctx, "/post_pb.PostsService/GetFolloweePosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) AddPost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*UserPostList, error) {
	out := new(UserPostList)
	err := c.cc.Invoke(ctx, "/post_pb.PostsService/AddPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) ClearAllPosts(ctx context.Context, in *Post, opts ...grpc.CallOption) (*PostPbStruct, error) {
	out := new(PostPbStruct)
	err := c.cc.Invoke(ctx, "/post_pb.PostsService/ClearAllPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetAllPosts(ctx context.Context, in *Post, opts ...grpc.CallOption) (*UserPostList, error) {
	out := new(UserPostList)
	err := c.cc.Invoke(ctx, "/post_pb.PostsService/GetAllPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsServiceServer is the server API for PostsService service.
type PostsServiceServer interface {
	GetFolloweePosts(context.Context, *PostPbStruct) (*UserPostList, error)
	AddPost(context.Context, *Post) (*UserPostList, error)
	ClearAllPosts(context.Context, *Post) (*PostPbStruct, error)
	GetAllPosts(context.Context, *Post) (*UserPostList, error)
}

// UnimplementedPostsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostsServiceServer struct {
}

func (*UnimplementedPostsServiceServer) GetFolloweePosts(context.Context, *PostPbStruct) (*UserPostList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFolloweePosts not implemented")
}
func (*UnimplementedPostsServiceServer) AddPost(context.Context, *Post) (*UserPostList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPost not implemented")
}
func (*UnimplementedPostsServiceServer) ClearAllPosts(context.Context, *Post) (*PostPbStruct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearAllPosts not implemented")
}
func (*UnimplementedPostsServiceServer) GetAllPosts(context.Context, *Post) (*UserPostList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPosts not implemented")
}

func RegisterPostsServiceServer(s *grpc.Server, srv PostsServiceServer) {
	s.RegisterService(&_PostsService_serviceDesc, srv)
}

func _PostsService_GetFolloweePosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostPbStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetFolloweePosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_pb.PostsService/GetFolloweePosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetFolloweePosts(ctx, req.(*PostPbStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_AddPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).AddPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_pb.PostsService/AddPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).AddPost(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_ClearAllPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).ClearAllPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_pb.PostsService/ClearAllPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).ClearAllPosts(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetAllPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetAllPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_pb.PostsService/GetAllPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetAllPosts(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "post_pb.PostsService",
	HandlerType: (*PostsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFolloweePosts",
			Handler:    _PostsService_GetFolloweePosts_Handler,
		},
		{
			MethodName: "AddPost",
			Handler:    _PostsService_AddPost_Handler,
		},
		{
			MethodName: "ClearAllPosts",
			Handler:    _PostsService_ClearAllPosts_Handler,
		},
		{
			MethodName: "GetAllPosts",
			Handler:    _PostsService_GetAllPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
